# 日志配置
logging:
  level:
    cc.sika: debug
    org.springframework: warn

# Spring配置
spring:
  profiles:
    active: dev
  # MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sika?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: ******
  # redis 配置
  redis:
    # 地址
    host: 192.168.*.*
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: ******
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # SpringBoot 2.6.x 版本与Swagger不兼容问题


# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: cc.sika.api.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

swagger:
  enabled: true
  title: "Sika-Question接口文档"
  version: 1.0
  base-path: /
  description: "问题操作相关接口"
  contact:
    email: 2235569493@qq.com
    name: 小吴来哩!
    url: http://ironcentury.cc

